# Generated by Django 4.1.3 on 2022-11-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100, verbose_name='Veiklos rūšis')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Regionas')),
            ],
            options={
                'ordering': ['region'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Statusas')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Imonė')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Kontaktinis asmuo')),
                ('address', models.CharField(max_length=200, verbose_name='Adresas')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.region')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.status')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_description', models.TextField(help_text='Trumpas veiklos aprašymas', max_length=1000, verbose_name='Veiklos aprašymas')),
                ('sold_units', models.IntegerField(verbose_name='Parduoti vienetai')),
                ('price_per_unit', models.IntegerField(verbose_name='Parduoto vieneto kaina')),
                ('date', models.DateField(verbose_name='Data')),
                ('date_next_activity', models.DateField(verbose_name='Kito kontakto data')),
                ('activity_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.activitytype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
