# Generated by Django 4.1.3 on 2022-11-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_activity_activity_type_alter_customer_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='customer@customer.com', max_length=254),
        ),
    ]
