# Generated by Django 4.1.3 on 2022-12-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
