# Generated by Django 4.1.3 on 2022-12-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
